spring:
  datasource:
    url: jdbc:mysql://localhost:1981/shop_axm
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password : root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
    update:
      mode: always

application:
  title: ShopAxm
  version: 1.0

logging:
  file:
    name: /var/log/shop/shop.log
  level:
    ro.pyc22: INFO

jwt:
  secret:
    something