server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_axm
    username: root
    driver: com.mysql.cj.jdbc.Driver
    password:


  jpa:
    generate-dll: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers : true

  sql:
    init:
      mode: always
    update:
      mode: always


application:
  title: ShopAnaxim
  version: 1.0

jwt:
  secret: something

upload:
  folder: C:/appImages/